blogs/urls.py
from django.urls import path

from . import views

app_name = "blogs"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:post_id>/", views.detail, name="detail"),
]

main/urls.py
from django.urls import path

from . import views

app_name = "main"
urlpatterns = [
    path("", views.index, name="index"),
    path("resume/", views.resume, name="resume"),
]

my_portfolio/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path("", include("main.urls")),
    path("projects/", include("projects.urls")),
    path("blogs/", include("blogs.urls")),
    path("admin/", admin.site.urls),
]

projects/urls.py
from django.urls import path

from . import views

app_name = "projects"
urlpatterns = [
    path("", views.index, name="index"),
]

main/models.py
from django.db import models


class Resume(models.Model):
    upload_date = models.DateTimeField(auto_now=True)
    resume_file = models.FileField(upload_to="resumes/", null=True, blank=True)

projects/models.py
from django.db import models
from django.urls import reverse
from django.db.models import UniqueConstraint
from django.db.models.functions import Lower
from django.contrib.auth.models import User


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)
    create_date = models.DateTimeField(auto_now_add=True)
    create_uid = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name="created_tags")
    write_date = models.DateTimeField(auto_now=True)
    write_uid = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name="written_tags")

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('tag-detail', args=[str(self.id)])
    
    class Meta:
        constraints = [
            UniqueConstraint(
                Lower("name"),
                name = "tag_name_case_insensitive_unique",
                violation_error_message = "Tag already exists (case insensitive match)."
            )
        ]


class Project(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to="project_images")
    description = models.CharField(max_length=255)
    tags = models.ManyToManyField(Tag)
    site = models.URLField(max_length=255)
    repo = models.URLField(max_length=255, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    create_uid = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name="created_projects")
    write_date = models.DateTimeField(auto_now=True)
    write_uid = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name="written_projects")

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('project-detail', args=[str(self.id)])
    
    def display_project(self):
        return ", ".join(tag.name for tag in self.tags.all())
    
    display_project.short_description = "Tags"

users/models.py
from django.db import models

# Create your models here.

blogs/views.py
from django.http import Http404
from django.shortcuts import render

from .utils import sort_list_of_dictionaries
from .odoo_api import OdooAPI

odoo_api = OdooAPI()

def index(request):
    posts = odoo_api.get_posts()
    posts.sort(key=sort_list_of_dictionaries)
    context = {"posts": posts, "title": "Blog"}
    return render(request, "blogs/index.html", context)

def detail(request, post_id):
    post = odoo_api.get_post(post_id)
    if not post:
        raise Http404("Post not found")
    context = {"post": post, "title": "Blog Detail"}
    return render(request, "blogs/detail.html", context)

main/views.py
from django.shortcuts import render
from django.http import FileResponse, Http404 

from .models import Resume


def index(request):
    context = {"title": "Home"}
    return render(request, "main/index.html", context)


def resume(request):
    resume = Resume.objects.last()
    if resume and resume.resume_file:
        try:
            response = FileResponse(resume.resume_file, content_type='application/pdf', as_attachment=False)
            return response
        except Exception:
            raise Http404("Resume file not found.")
    raise Http404("No resume available.")

projects/views.py
from django.shortcuts import render

from .models import Project


def index(request):
    projects = Project.objects.order_by("name").all()
    context = {"projects": projects, "title": "Projects"}
    return render(request, "projects/index.html", context)

users/views.py
from django.shortcuts import render

# Create your views here.

blogs/templates/blogs/detail.html
{% extends "main/base.html" %}
{% block content %}
    <section id="detail-section">
        <div class="row justify-content-evenly">
            <div class="col-md-7">
                <h1>{{ post.name }}</h1>
                <div class="post-content">{{ post.content | safe }}</div>
            </div>
        </div>
    </section>
{% endblock content %}

blogs/templates/blogs/index.html
{% extends "main/base.html" %}
{% block content %}
    <section id="blogs-section" class="flex-wrap d-flex justify-content-center">
        {% if posts %}
            {% for post in posts %}
                <a href="{% url 'blogs:detail' post.id %}" class="post-link">
                    <div class="card mb-4 mx-md-3" style="max-width:350px;">
                        <div class="card-image-container">
                            <img src="{{ post.image_url }}" class="card-img-top card-image" alt="{{ post.name }}">
                            <div class="post-author-overlay ms-3 py-1"><i class="fa-solid fa-user me-2"></i></i>{{ post.author_name }}</div>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title mb-3">{{ post.name }}</h5>
                            <p class="card-text card-content post-content text-body-secondary">{{ post.content | striptags }}</p>
                            <p class="card-text"><small>{{ post.published_date }}</small></p>
                        </div>
                    </div>
                </a>
            {% endfor %}
        {% else %}
            <div class="empty-context text-center my-5 py-5">
                <h2>Oops, no blog has been published.</h2>
            </div>
        {% endif %}
    </section>
{% endblock content %}

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
        <title>Cris-aian Vergara | {{ title }} </title>
    {% else %}
        <title>Cris-aian Vergara</title>
    {% endif %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
        crossorigin="anonymous" />
    {% load static %}
    <link rel="icon" href="{% static 'main/favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'projects/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blogs/style.css' %}">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" 
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav m-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:index' %}">01 : Home</a>
                        </li>
                        <li class="nav-item d-none d-lg-block"><a class="nav-link nav-link-vertical-line">|</a></li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'projects:index' %}">02 : Projects</a>
                        </li>
                        <li class="nav-item d-none d-lg-block"><a class="nav-link nav-link-vertical-line">|</a></li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blogs:index' %}">03 : Blog</a>
                        </li>
                        <li class="nav-item d-none d-lg-block"><a class="nav-link nav-link-vertical-line">|</a></li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:resume' %}" target="_blank" rel="noopener noreferrer">04 : Resume</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container"><hr class="m-0 p-0" /></div>
    </header>
    <main class="container my-5 py-4">
        {% block content %}{% endblock %}
    </main>
    <footer class="text-center">
        <div class="social-links">
            <ul>
                <li class="nav-item">
                    <a class="nav-link" href="https://www.linkedin.com/in/crisaianvergara/" target="_blank">
                        <i class="fa-brands fa-linkedin"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://github.com/crisaianvergara" target="_blank">
                        <i class="fa-brands fa-square-github"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://www.facebook.com/crisaianvergara" target="_blank">
                        <i class="fa-brands fa-square-facebook"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://www.instagram.com/aian.vergara/" target="_blank">
                        <i class="fa-brands fa-square-instagram"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://gitlab.com/crisaianvergara" target="_blank">
                        <i class="fa-brands fa-square-gitlab"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="mailto:crisaianvergara@gmail.com" target="_blank">
                        <i class="fa-solid fa-envelope"></i>
                    </a>
                </li>
            </ul>
        </div>
        <div class="container"><hr /></div>
        <p class="copy">&copy; Cris-aian Vergara <span id="year">2015</span></p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" 
        crossorigin="anonymous">
    </script>
    <script src="{% static 'main/script.js' %}"></script>
    <script src="https://kit.fontawesome.com/543a846626.js" crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/index.html
{% extends "main/base.html" %}
{% block content %}
    <section id="home-section">
        <h1>Hello, I am Cris-aian.</h1>
        <h3>Full Stack Developer</h3>
        <div id="home-bottom-space"></div>
    </section>
{% endblock content %}

projects/templates/projects/index.html
{% extends "main/base.html" %}
{% block content %}
    <section id="projects-section" class="flex-wrap d-flex justify-content-center">
        {% if projects %}
            {% for project in projects %}
                <div class="card mb-4 mx-md-3" style="max-width:350px;">
                    <div class="card-image-container">
                        <img src="{{ project.image.url }}" class="card-img-top card-image" alt="{{ project.name }}">
                    </div>
                    <div class="card-body">
                        <h5 class="card-title mb-3">{{ project.name }}</h5>
                        <p class="card-text card-content text-body-secondary">{{ project.description }}</p>
                        {% if project.tags.all %}
                            <div class="tags">
                                <ul>
                                    {% for tag in project.tags.all %}
                                        <li class="badge rounded-pill text-bg-primary"">{{ tag }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}
                    </div>
                    <div class="card-footer bg-white pb-0">
                        <ul class="card-footer-link flex-wrap d-flex justify-content-evenly">
                            <li><a class="card-link text-secondary" href="{{ project.site }}" target="_blank"><i class="fa-solid fa-eye"></i></a></li>
                            <span class="card-link text-secondary">|</span>
                            {% if project.repo %}
                                <li><a class="card-link text-secondary" href="{{ project.repo }}" target="_blank"><i class="fa-brands fa-github"></i></a></li>
                            {% else %}
                                
                                <li><span class="card-link text-secondary"><i class="fa-solid fa-circle-xmark"></i></span></li>
                            {% endif %}    
                            </ul>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="empty-context text-center my-5 py-5">
                <h2>Oops, empty projects.</h2>
            </div>
        {% endif %}
    </section>
{% endblock content %}